#!/bin/bash

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi


red="\033{0;31m"
normal="\033[0m"

echo -e $red "Installation de most" $normal
dnf install -y most
echo $red "done" $normal

echo -e $red "Installation de terminator" $normal
dnf install -y terminator
echo $red "done" $normal

echo -e $red "Installation de Htop" $normal
dnf install -y htop
echo $red "done" $normal

echo -e $red "Installation de gcc et g++" $normal
dnf install -y gcc gcc-c++
echo $red "Fait" $normal

echo $red "Installation d'emacs" $normal
dnf install -y emacs
echo "alias emacs=\"emacs -nw\"" >> ~/.bashrc
echo "alias ne=\"emacs\"" >> ~/.bashrc
echo  $red "done" $normal

echo $red "Installations de lib perso" $normal
dnf install -y glew glew-devel

echo $red "SFML2.3" $normal
dnf install -y SFML-devel-2.3-1.fc23.x86_64

echo $red "OpenGL" $normal
dnf install -y freeglut-devel-3.0.0-2.fc23.x86_64 

echo $red "SDL1.2 + SDL2 + deps" $normal
dnf install -y SDL2-devel-2.0.3-7.fc23.x86_64
dnf install -y SDL2_image-devel-2.0.0-8.fc23.x86_64
dnf install -y SDL2_mixer-devel-2.0.1-1.fc23.x86_64
dnf install -y SDL2_ttf-devel-2.0.13-1.fc23.x86_64
dnf install -y SDL-devel-1.2.15-20.fc23.x86_64
dnf install -y SDL_image-devel-1.2.12-13.fc23.x86_64
dnf install -y SDL_mixer-devel-1.2.12-10.fc23.x86_64
dnf install -y SDL_ttf-devel-2.0.11-7.fc23.x86_64

echo $red "libcaca" $normal
dnf install -y libcaca-devel-0.99-0.25.beta18.fc23.x86_64
echo $red "done" $normal

echo $red "installing valgrind" $normal
dnf install -y valgrind-devel-1\:3.11.0-18.fc23.x86_64
echo $red "done" $normal

echo $red "installing atom" $normal
wget https://github.com/atom/atom/releases/download/v1.6.2/atom.x86_64.rpm
dnf install -y ./atom.x86_64.rpm
mv atom.x86_64.rpm /tmp
echo $red "done" $normal
 
echo $red "installing blih" $normal
wget https://raw.githubusercontent.com/BadPinkChicken/blih2exe/master/blih.py
chmod 777 blih.py
mv blih.py /usr/bin/blih
echo $red "done" $normal

echo $red "Upgrading pip NOPE" $normal
##pip install --upgrade pip
echo $red "done" $normal

echo $red "installingr eg" $normal
pip install eg
echo $red "done" $normal


##echo $red "Getting conf files" $normal
##wget http://salnikoff.fr/tekstuff/conf_files.tar.gz
##tar zxvf conf_files.tar.gz
##cp -v -r ./conf_files/. /home/$1
##mv ./conf_files /tmp/
##mv ./conf_files.tar.gz /tmp
echo "done"

